### ISSUE TITLE
Header File Generation Errors Due to Typo

### ISSUE THREAD

**Issue by bowenXuu** [siyuanwu99/pred-occ-planner#3]
Hi, it's me, Bowen, I found a small problem in the compilation. To locate the bug, you can navigate to the following path:

```shell
cd uav_simulator/multi_map_server
```

In **line 176** of `CMakeLists.txt`, I assume you want to rely on the correct message generation target. Normally this would be 

```make
${PROJECT_NAME}_generate_messages_cpp
```

However, I noticed that there was a missing "generate" which was causing the `.msg` to not generate the `.h` file correctly when I ran `catkin build`, so I made the following change.

```make
#add_dependencies(multi_map_visualizationmulti_map_server_messages_cpp)
add_dependencies(multi_map_visualization multi_map_server_generate_messages_cpp)
```

Now the project compiles fine, and if we're on the same page, you might want to consider updating your source code!

**Comment by siyuanwu99** [comment]
Thank you for your kind feedback, and sorry for any trouble this issue may cause! I will update the code and sync the latest changes in the past few months in this project.
